#!/usr/bin/env bash
# Regenerate the harness block in ~/.pi/agent/AGENTS.md.
#
# Pi has no SessionStart hook, so the payload that Claude Code gets from
# skills-session-start.sh goes into Pi's global context file instead — loaded
# into every session, before project trust is resolved, and preserved across
# compaction.
#
# Everything between the markers is generated from the local (rewritten)
# using-superpowers copy plus pi-agents-header.md. Anything outside them is
# yours and is left alone.
#
# install.sh and refresh-superpowers-skills.sh --apply both call this; run it
# yourself after editing using-superpowers by hand.
set -euo pipefail

SKILL="${HARNESS_SUPERPOWERS_SKILL:-$HOME/.claude/skills/using-superpowers/SKILL.md}"
HEADER="${HARNESS_PI_HEADER:-$HOME/.claude/scripts/pi-agents-header.md}"
OUT="${HARNESS_PI_AGENTS:-$HOME/.pi/agent/AGENTS.md}"

[ -f "$SKILL" ]  || { echo "no using-superpowers skill at $SKILL" >&2; exit 66; }
[ -f "$HEADER" ] || { echo "no header fragment at $HEADER" >&2; exit 66; }

mkdir -p "$(dirname "$OUT")"
exec python3 - "$SKILL" "$HEADER" "$OUT" <<'PY'
import pathlib, sys

skill, header, out = (pathlib.Path(p) for p in sys.argv[1:4])
BEGIN = "<!-- harness:begin -->"
END = "<!-- harness:end -->"

body = header.read_text().rstrip().replace("{{USING_SUPERPOWERS}}", skill.read_text().strip())
block = "\n".join([
    BEGIN,
    "<!-- Generated by sync-pi-agents.sh from using-superpowers. Edits inside are lost. -->",
    body,
    END,
])

existing = out.read_text() if out.exists() else ""
if BEGIN in existing and END in existing:
    pre, rest = existing.split(BEGIN, 1)
    post = rest.split(END, 1)[1]
    new = pre + block + post
    what = "updated"
else:
    prefix = existing.rstrip() + "\n\n" if existing.strip() else ""
    new = prefix + block + "\n"
    what = "created" if not existing.strip() else "appended"

if new != existing:
    out.write_text(new)
print(f"   \033[32m✓\033[0m {out} — harness block {what} ({len(block.splitlines())} lines)")
PY
